### ISSUE TITLE
Switch to serde

### ISSUE THREAD

**Issue by theaddonn** [bedrock-crustaceans/bedrockrs#1]
The proto impl uses its own serialization/deserialization lib right now.
It would also be useful for the nbt impl to get serde support.
The switch to serde should definitly happen.

**Comment by Adrian8115** [comment]
It is not intended for `Proto` anymore due to being not useful enough, but it may be for `Nbt`

**Comment by theaddonn** [comment]
this is now a feature over at our moved nbt library https://github.com/bedrock-crustaceans/bedrockrs-nbt
