### ISSUE TITLE
Fix dependabot

### ISSUE THREAD

**Issue by theaddonn** [bedrock-crustaceans/bedrockrs#57]
We're currently using dependabot to auto update our deps, but dependabot only currently detects the main manifest in the project root. It would be amicable if we could adjust it so that also sub crate manifests are checked. This would be possible via wildcards, tho I am unsure if they are currently implemented

**Comment by heydocode** [comment]
Fixed with [`this PR`](https://github.com/bedrock-crustaceans/bedrockrs/pull/61)
