### ISSUE TITLE
Add `BigEndian` and `BigEndianNetwork` to nbt

### ISSUE THREAD

**Issue by theaddonn** [bedrock-crustaceans/bedrockrs#6]
Both are rarely/never used in mcbe, so this is low priority

- [X] `Big Endian`
- [x] `Big Endian Network`

**Comment by Adrian8115** [comment]
`Big Endian` has been added

**Comment by theaddonn** [comment]
this issue should be closed now since the nbt library has been moved over to https://github.com/bedrock-crustaceans/bedrockrs-nbt
