### ISSUE TITLE
set_title function error

### ISSUE THREAD

**Issue by Inotart** [bedrock-crustaceans/bedrockrs#73]
![image](https://github.com/user-attachments/assets/27778f33-226a-45a3-a77b-b253a02e2a61)

`rust
use xuid::Xuid;
use bedrockrs_core::int::VAR;

use crate::connection::ConnectionShard;
use crate::error::LoginError;
use crate::gamepackets::GamePackets;
use crate::login::provider::{LoginProviderServer, LoginProviderStatus};
use crate::packets::play_status::PlayStatusPacket;
use crate::packets::set_title::SetTitlePacket;
use crate::types::play_status::PlayStatusType;
use crate::types::title_type::TitleType;

pub async fn set_title(
    conn: &mut ConnectionShard,
    provider: &mut impl LoginProviderServer,
) -> Result<(), LoginError> {
    //////////////////////////////////////
    //  Set Title
    //////////////////////////////////////

    let set_title = SetTitlePacket {
        title_type: TitleType::Title,
        title_text: String::from("hello_text"),
        fade_in_time: VAR::new(500),
        stay_time: VAR::new(500),
        fade_out_time: VAR::new(500),
        xuid: Xuid::from(123456789),
        platform_online_id: String::from("hello_platform_online_id"),
    };

    match conn.send(GamePackets::SetTitle(set_title)).await {
        Ok(_) => {}
        Err(e) => return Err(LoginError::ConnectionError(e)),
    }

    match conn.flush().await {
        Ok(_) => {}
        Err(e) => return Err(LoginError::ConnectionError(e)),
    };

    Ok(())
}
`
Xuid::from(123456789) cannot run. Then I tried to query the doc for xuid. Changed to xuid: xuid::xuid!(123456789).unwrap(), I don't think it's a good solution, and hopefully it can be resolved.

**Comment by theaddonn** [comment]
You should try out the `proto-rework` branch! It fixed the bug if I recall correctly
